<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="OB-Nom34" failures="1" tests="1" name="NewLedgerCodeCTPftLos.TC01LedgerCode_7511CharitableDonations" time="84.441" errors="0" timestamp="2022-03-15T12:08:11 IST" skipped="0">
  <testcase classname="NewLedgerCodeCTPftLos.TC01LedgerCode_7511CharitableDonations" name="LedgerCode_CTAdjstment_ProfitLoss_CharitableDonations_Debit" time="84.441">
    <failure message="Ledger Balance did not match in FA CT_Adjustment expected [1,600.00] but found [1600.00]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Ledger Balance did not match in FA CT_Adjustment expected [1,600.00] but found [1600.00]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at page.factories.CT_Adjustment_ProfitLossTab.VerifyLedgerValue(CT_Adjustment_ProfitLossTab.java:184)
at NewLedgerCodeCTPftLos.TC01LedgerCode_7511CharitableDonations.LedgerCode_CTAdjstment_ProfitLoss_CharitableDonations_Debit(TC01LedgerCode_7511CharitableDonations.java:155)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- LedgerCode_CTAdjstment_ProfitLoss_CharitableDonations_Debit -->
  <system-out/>
</testsuite> <!-- NewLedgerCodeCTPftLos.TC01LedgerCode_7511CharitableDonations -->
